export const testSentences = {
  // 25 Questions
  "why did you choose this architecture": "QUESTION",
  "how did you handle unexpected blockers": "QUESTION",
  "can you walk me through your deployment process": "QUESTION",
  "what tools did you use for testing": "QUESTION",
  "when did you complete the first milestone": "QUESTION",
  "who was responsible for stakeholder communication": "QUESTION",
  "do you have experience with cloud migrations": "QUESTION",
  "could you share lessons learned from this project": "QUESTION",
  "how big was your team during the rollout": "QUESTION",
  "what challenges came up during user acceptance testing": "QUESTION",
  "this was a tight deadline wasn’t it": "QUESTION",
  "you took full ownership of delivery right": "QUESTION",
  "they trusted you with critical features didn’t they": "QUESTION",
  "is there anything you would do differently next time": "QUESTION",
  "how do you measure success for this product": "QUESTION",
  "are you comfortable working in distributed teams": "QUESTION",
  "could you explain your prioritization strategy": "QUESTION",
  "why did the client approve your proposal so quickly": "QUESTION",
  "what improvements did you see after launch": "QUESTION",
  "how would you handle conflicting priorities": "QUESTION",
  "this budget was quite limited correct": "QUESTION",
  "do you prefer working on frontend or backend": "QUESTION",
  "was the customer satisfied with the final result": "QUESTION",
  "how did you ensure high availability": "QUESTION",
  "what is the biggest risk you faced on that project": "QUESTION",

  // 25 Statements
  "the budget was reduced mid project": "STATEMENT",
  "we avoided any major production incidents": "STATEMENT",
  "that was your biggest challenge so far": "STATEMENT",
  "they assigned you to lead the new initiative": "STATEMENT",
  "this outcome exceeded the stakeholders expectations": "STATEMENT",
  "they needed quick results so you delivered early": "STATEMENT",
  "your manager supported your promotion": "STATEMENT",
  "the migration completed last month without major issues": "STATEMENT",
  "we finished onboarding the new hires on time": "STATEMENT",
  "the project wrapped up before the end of the quarter": "STATEMENT",
  "our release improved performance across the system": "STATEMENT",
  "the final product met all requirements": "STATEMENT",
  "their feedback was positive after launch": "STATEMENT",
  "we implemented a consistent design system": "STATEMENT",
  "the timeline stayed realistic through each phase": "STATEMENT",
  "the client signed off on the final scope": "STATEMENT",
  "they offered us an extension for the next phase": "STATEMENT",
  "we kept stakeholders informed with weekly demos": "STATEMENT",
  "they provided a dedicated resource to help us": "STATEMENT",
  "my team managed to remove technical debt": "STATEMENT",
  "the integration required several cross team discussions": "STATEMENT",
  "we had no blockers during the final testing": "STATEMENT",
  "the adoption rate was higher than we expected": "STATEMENT",
  "security compliance was verified in the audit": "STATEMENT",
  "the roadmap aligned with overall business goals": "STATEMENT",
   "how do you handle merging conflicts in git": "QUESTION",
  "what design patterns do you typically use": "QUESTION",
  "how would you debug a memory leak in production": "QUESTION",
  "can you explain the difference between rest and graphql": "QUESTION",
  "what considerations do you make for scalability": "QUESTION",
  "do you have experience with container orchestration": "QUESTION",
  "could you walk me through your ci cd pipeline": "QUESTION",
  "how did you validate your load testing results": "QUESTION",
  "what tradeoffs did you make in your architecture choices": "QUESTION",
  "when did you last refactor a legacy module": "QUESTION",
  "who was responsible for code reviews on your team": "QUESTION",
  "are you familiar with domain driven design": "QUESTION",
  "how would you design a multi tenant application": "QUESTION",
  "could you describe your experience with message queues": "QUESTION",
  "why did you choose that database technology": "QUESTION",
  "what are the biggest security concerns in this project": "QUESTION",
  "how do you monitor system health in production": "QUESTION",
  "what experience do you have with distributed systems": "QUESTION",
  "did you participate in backlog refinement sessions": "QUESTION",
  "how would you enforce consistency across microservices": "QUESTION",
  "can you describe a time you disagreed with a tech lead": "QUESTION",
  "what frameworks do you prefer for unit testing": "QUESTION",
  "how do you prioritize bug fixes against new features": "QUESTION",
  "what is your approach to handling incidents": "QUESTION",
  "how would you estimate story points for a complex task": "QUESTION",
  "could you explain the principle of fail fast": "QUESTION",
  "why did you choose a monorepo over polyrepo": "QUESTION",
  "do you have experience working with feature flags": "QUESTION",
  "how did you ensure code quality in a large team": "QUESTION",
  "what steps do you take to write maintainable code": "QUESTION",
  "how would you handle a sudden spike in user traffic": "QUESTION",
  "are you comfortable writing integration tests": "QUESTION",
  "what is your understanding of event driven architecture": "QUESTION",
  "how do you approach documenting complex systems": "QUESTION",
  "what is your process for onboarding new engineers": "QUESTION",
  "why did you decide to use a service mesh": "QUESTION",
  "how would you design a resilient notification system": "QUESTION",
  "can you explain the difference between optimistic and pessimistic locking": "QUESTION",
  "do you follow test driven development in your work": "QUESTION",
  "what observability tools do you prefer": "QUESTION",
  "how do you approach breaking down large tasks": "QUESTION",
  "could you describe a time you had to pivot on a feature": "QUESTION",
  "when was the last time you updated your dependencies": "QUESTION",
  "who usually signs off on production releases in your team": "QUESTION",
  "how do you handle feature rollbacks": "QUESTION",
  "what are the key metrics you track post release": "QUESTION",
  "how do you handle parallel feature development": "QUESTION",
  "are you comfortable managing incidents out of hours": "QUESTION",
  "why is code simplicity important in your opinion": "QUESTION",
  "can you explain the concept of blue green deployments": "QUESTION",
  "how do you handle secrets management in cloud": "QUESTION",
  "what performance bottlenecks have you encountered": "QUESTION",
  "how do you decide what to refactor and when": "QUESTION",
  "could you explain how you estimate capacity planning": "QUESTION",
  "when do you typically do technical spikes": "QUESTION",
  "how do you work with product managers on prioritization": "QUESTION",
  "what is your strategy for reducing technical debt": "QUESTION",
  "how would you ensure data integrity across services": "QUESTION",
  "do you think pair programming is effective": "QUESTION",
  "what are your thoughts on monolithic versus microservice": "QUESTION",
  "how do you ensure performance for mobile users": "QUESTION",
  "why is observability important in modern systems": "QUESTION",
  "could you walk me through a production outage you handled": "QUESTION",
  "when do you recommend using a nosql database": "QUESTION",
  "how do you handle rollback for database migrations": "QUESTION",
  "can you describe how you measure product adoption": "QUESTION",
  "what tools do you use for log aggregation": "QUESTION",
  "how do you coordinate deployments across regions": "QUESTION",
  "who takes ownership of bug triage in your projects": "QUESTION",
  "why did you select that programming language for the project": "QUESTION",
  "do you automate infrastructure provisioning": "QUESTION",
  "what is your approach for feature toggles": "QUESTION",
  "how do you approach security reviews": "QUESTION",
  "could you describe a tricky production issue you resolved": "QUESTION",
  "what is your preferred branching strategy": "QUESTION",
  "how do you balance innovation with stability": "QUESTION",
  "why would you choose eventual consistency": "QUESTION",
  "how did you validate performance improvements": "QUESTION",
  "what strategies do you use for cache invalidation": "QUESTION",
  "are you comfortable running blameless postmortems": "QUESTION",
  "how do you handle breaking changes in apis": "QUESTION",
  "what is your understanding of chaos engineering": "QUESTION",
  "could you explain the difference between vertical and horizontal scaling": "QUESTION",
  "how do you approach dependency management": "QUESTION",
  "what are your thoughts on legacy code refactoring": "QUESTION",
  "why is code readability important to you": "QUESTION",
  "how do you communicate risk to non technical stakeholders": "QUESTION",
  "could you explain how you set up staging environments": "QUESTION",
  "when do you typically conduct load testing": "QUESTION",
  "how do you approach setting service level objectives": "QUESTION",
  "what tools do you recommend for end to end testing": "QUESTION",
  "how do you coordinate with designers during development": "QUESTION",
  "why is backward compatibility important": "QUESTION",
  "can you describe a time you advocated for a technical change": "QUESTION",
  "what experience do you have with infrastructure as code": "QUESTION",
  "how do you ensure your team meets delivery commitments": "QUESTION",
  "could you explain how you handled a missed deadline": "QUESTION",
  "what is your view on code ownership versus collective ownership": "QUESTION",
  "I dont understand what you are saying":"QUESTION",


  "what is your experience with serverless architectures": "QUESTION",
  "how would you secure an api from unauthorized access": "QUESTION",
  "can you explain the concept of zero trust security": "QUESTION",
  "how do you plan for horizontal scaling": "QUESTION",
  "what steps do you take to reduce latency": "QUESTION",
  "could you describe your experience with feature branching": "QUESTION",
  "when would you choose event sourcing": "QUESTION",
  "why did you use a message broker for this system": "QUESTION",
  "how do you coordinate database schema changes": "QUESTION",
  "what logging framework do you typically use": "QUESTION",
  "how do you ensure high throughput in your applications": "QUESTION",
  "what methods do you use for root cause analysis": "QUESTION",
  "are you comfortable handling secrets rotation": "QUESTION",
  "how do you monitor third party service dependencies": "QUESTION",
  "could you explain the concept of circuit breaker": "QUESTION",
  "what is your approach for validating user input": "QUESTION",
  "how do you build scalable api gateways": "QUESTION",
  "when would you use a relational database over nosql": "QUESTION",
  "how do you decide the granularity of microservices": "QUESTION",
  "could you describe a time you had to resolve team conflict": "QUESTION",
  "what tools do you use for static code analysis": "QUESTION",
  "how do you verify rollback strategies work in production": "QUESTION",
  "what are the best practices for api versioning": "QUESTION",
  "why is observability essential for cloud native applications": "QUESTION",
  "could you walk me through your disaster recovery planning": "QUESTION",
  "how do you avoid vendor lock in when using cloud services": "QUESTION",
  "what techniques do you use for load balancing": "QUESTION",
  "when did you last review your security posture": "QUESTION",
  "who usually participates in post incident reviews": "QUESTION",
  "how do you estimate performance under peak load": "QUESTION",
  "what experience do you have with multi region deployments": "QUESTION",
  "how do you coordinate with stakeholders on requirements": "QUESTION",
  "could you explain the purpose of a design spike": "QUESTION",
  "when would you recommend using a graph database": "QUESTION",
  "why do you think clean code is so valuable": "QUESTION",
  "how do you handle testing asynchronous workflows": "QUESTION",
  "what steps do you take to validate performance regressions": "QUESTION",
  "do you have experience with headless cms platforms": "QUESTION",
  "how do you keep security top of mind during development": "QUESTION",
  "what is your process for accessibility testing": "QUESTION",
  "when would you use a pub sub architecture": "QUESTION",
  "how do you track user behavior for product analytics": "QUESTION",
  "why is resilience important in distributed systems": "QUESTION",
  "can you describe how you built a proof of concept": "QUESTION",
  "what frameworks do you prefer for end to end tests": "QUESTION",
  "how do you balance cost and performance in cloud systems": "QUESTION",
  "when do you typically schedule refactoring tasks": "QUESTION",
  "who usually coordinates releases in your team": "QUESTION",
  "how do you plan feature rollouts for a global audience": "QUESTION",
  "what is your experience with authentication and authorization": "QUESTION",
  "how do you stay current with emerging technologies": "QUESTION",
  "could you explain why you chose a certain caching strategy": "QUESTION",
  "when would you implement optimistic concurrency": "QUESTION",
  "why is idempotency important in api design": "QUESTION",
  "how do you design for graceful degradation": "QUESTION",
  "what techniques do you use for progressive rollout": "QUESTION",
  "how do you avoid scope creep during projects": "QUESTION",
  "what process do you follow for sprint planning": "QUESTION",
  "how do you test for cross browser compatibility": "QUESTION",
  "when would you leverage server side rendering": "QUESTION",
  "who is responsible for incident response in your team": "QUESTION",
  "how do you manage shared dependencies across microservices": "QUESTION",
  "what strategies do you use for incremental delivery": "QUESTION",
  "why do you think retrospectives are important": "QUESTION",
  "could you describe a difficult technical decision you made": "QUESTION",
  "what is your process for defining acceptance criteria": "QUESTION",
  "how do you coordinate load testing with other teams": "QUESTION",
  "when do you consider a feature ready for production": "QUESTION",
  "who usually signs off on architecture decisions": "QUESTION",
  "how do you address privacy concerns with data collection": "QUESTION",
  "what is your view on manual versus automated testing": "QUESTION",
  "how do you handle onboarding new developers to a complex system": "QUESTION",
  "what factors do you consider when choosing a framework": "QUESTION",
  "why did you adopt a micro frontend approach": "QUESTION",
  "how do you monitor container health in production": "QUESTION",
  "what tools do you use for performance profiling": "QUESTION",
  "when do you typically do user acceptance testing": "QUESTION",
  "who reviews code for security vulnerabilities": "QUESTION",
  "how do you validate a design hypothesis": "QUESTION",
  "what is your strategy for avoiding downtime": "QUESTION",
  "how do you coordinate large scale migrations": "QUESTION",
  "could you describe your experience with infrastructure scaling": "QUESTION",
  "why do you prioritize developer experience": "QUESTION",
  "how do you align technical goals with product goals": "QUESTION",
  "what is your experience with hybrid cloud environments": "QUESTION",
  "how do you coordinate across multiple scrum teams": "QUESTION",
  "when would you recommend feature branches versus trunk based development": "QUESTION",
  "who usually coordinates roadmap planning": "QUESTION",
  "how do you work with qa engineers on test coverage": "QUESTION",
  "what tools do you recommend for infrastructure monitoring": "QUESTION",
  "how do you analyze and prevent single points of failure": "QUESTION",
  "when do you prefer build versus buy decisions": "QUESTION",
  "who owns the backlog grooming in your projects": "QUESTION",
  "what is your approach to documentation updates": "QUESTION",
  "how do you measure the success of a technical spike": "QUESTION",
  "why do you think postmortems should be blameless": "QUESTION",
  "could you explain the difference between active active and active passive": "QUESTION",
  "what tradeoffs did you make on the last architecture decision": "QUESTION",
  "how do you structure onboarding for junior engineers": "QUESTION",
  "when do you usually discuss technical debt with product managers": "QUESTION",
  "what is your experience with cloud cost optimization": "QUESTION"
};
