export const testSentences = {
  // 25 Questions
  "why did you choose this architecture": "QUESTION",
  "how did you handle unexpected blockers": "QUESTION",
  "can you walk me through your deployment process": "QUESTION",
  "what tools did you use for testing": "QUESTION",
  "when did you complete the first milestone": "QUESTION",
  "who was responsible for stakeholder communication": "QUESTION",
  "do you have experience with cloud migrations": "QUESTION",
  "could you share lessons learned from this project": "QUESTION",
  "how big was your team during the rollout": "QUESTION",
  "what challenges came up during user acceptance testing": "QUESTION",
  "this was a tight deadline wasn’t it": "QUESTION",
  "you took full ownership of delivery right": "QUESTION",
  "they trusted you with critical features didn’t they": "QUESTION",
  "is there anything you would do differently next time": "QUESTION",
  "how do you measure success for this product": "QUESTION",
  "are you comfortable working in distributed teams": "QUESTION",
  "could you explain your prioritization strategy": "QUESTION",
  "why did the client approve your proposal so quickly": "QUESTION",
  "what improvements did you see after launch": "QUESTION",
  "how would you handle conflicting priorities": "QUESTION",
  "this budget was quite limited correct": "QUESTION",
  "do you prefer working on frontend or backend": "QUESTION",
  "was the customer satisfied with the final result": "QUESTION",
  "how did you ensure high availability": "QUESTION",
  "what is the biggest risk you faced on that project": "QUESTION",

  // 25 Statements
  "the budget was reduced mid project": "STATEMENT",
  "we avoided any major production incidents": "STATEMENT",
  "that was your biggest challenge so far": "STATEMENT",
  "they assigned you to lead the new initiative": "STATEMENT",
  "this outcome exceeded the stakeholders expectations": "STATEMENT",
  "they needed quick results so you delivered early": "STATEMENT",
  "your manager supported your promotion": "STATEMENT",
  "the migration completed last month without major issues": "STATEMENT",
  "we finished onboarding the new hires on time": "STATEMENT",
  "the project wrapped up before the end of the quarter": "STATEMENT",
  "our release improved performance across the system": "STATEMENT",
  "the final product met all requirements": "STATEMENT",
  "their feedback was positive after launch": "STATEMENT",
  "we implemented a consistent design system": "STATEMENT",
  "the timeline stayed realistic through each phase": "STATEMENT",
  "the client signed off on the final scope": "STATEMENT",
  "they offered us an extension for the next phase": "STATEMENT",
  "we kept stakeholders informed with weekly demos": "STATEMENT",
  "they provided a dedicated resource to help us": "STATEMENT",
  "my team managed to remove technical debt": "STATEMENT",
  "the integration required several cross team discussions": "STATEMENT",
  "we had no blockers during the final testing": "STATEMENT",
  "the adoption rate was higher than we expected": "STATEMENT",
  "security compliance was verified in the audit": "STATEMENT",
  "the roadmap aligned with overall business goals": "STATEMENT"
};
