questions = [
    "What is your name",
    "How old are you",
    "Where do you live",
    "When did you graduate",
    "Why did you leave the company",
    "Can you explain your experience",
    "Do you have any references",
    "Could you please clarify that",
    "What skills do you have",
    "How do you handle stress",
    "Would you be willing to relocate",
    "Did you manage a team",
    "Are you available on weekends",
    "What programming languages do you know",
    "Which project are you most proud of",
    "How do you stay motivated",
    "Have you ever worked remotely",
    "Is this your first interview",
    "What is your greatest strength",
    "What is your greatest weakness",
    "Can you tell me about a challenge you overcame",
    "Why are you interested in this role",
    "Do you have any leadership experience",
    "Could you describe your last project",
    "What would your previous manager say about you",
    "How do you prioritize tasks",
    "When can you start",
    "How do you approach problem-solving",
    "What motivates you",
    "Can you give an example of teamwork",
    "What are your career goals",
    "How do you handle conflict",
    "Why should we hire you",
    "Can you explain this gap in your resume",
    "Are you comfortable with travel",
    "How soon can you join",
    "What are your salary expectations",
    "How did you hear about us",
    "What certifications do you hold",
    "Do you have questions for us",
    "How would you describe yourself",
    "Why are you changing jobs",
    "What have you learned from mistakes",
    "Are you a team player",
    "Which environment do you prefer to work in",
    "Would you consider a different role",
    "What achievements are you most proud of",
    "How would you handle tight deadlines",
    "What is your name",
    "How old are you",
    "Where do you live",
    "When did you graduate",
    "Why did you leave the company",
    "Can you explain your experience",
    "Do you have any references",
    "Could you please clarify that",
    "What skills do you have",
    "How do you handle stress",
    "Would you be willing to relocate",
    "Did you manage a team",
    "Are you available on weekends",
    "What programming languages do you know",
    "Which project are you most proud of",
    "How do you stay motivated",
    "Have you ever worked remotely",
    "Is this your first interview",
    "What is your greatest strength",
    "What is your greatest weakness",
    "Can you tell me about a challenge you overcame",
    "Why are you interested in this role",
    "Do you have any leadership experience",
    "Could you describe your last project",
    "What would your previous manager say about you",
    "How do you prioritize tasks",
    "When can you start",
    "How do you approach problem-solving",
    "What motivates you",
    "Can you give an example of teamwork",
    "What are your career goals",
    "How do you handle conflict",
    "Why should we hire you",
    "Can you explain this gap in your resume",
    "Are you comfortable with travel",
    "How soon can you join",
    "What are your salary expectations",
    "How did you hear about us",
    "What certifications do you hold",
    "Do you have questions for us",
    "How would you describe yourself",
    "Why are you changing jobs",
    "What have you learned from mistakes",
    "Are you a team player",
    "Which environment do you prefer to work in",
    "Would you consider a different role",
    "What achievements are you most proud of",
    "How would you handle tight deadlines",
    "Is this your final answer",
    "Can you provide a reference",
    "How will you manage multiple tasks",
    "Why do you think this job is a good fit",
    "Who gave you this opportunity",
    "Do you think you are qualified",
    "Are you open to flexible hours",
    "Should we consider you for other roles",
    "Will you be available next month",
    "Would you recommend this company",
    "How did you prepare for this interview",
    "When can you travel",
    "Why do you prefer remote work",
    "Where did you hear about this opening",
    "What inspired you to apply",
    "Who was your last manager",
    "Can you commit to long-term work",
    "Is relocation an issue for you",
    "Do you have experience in team leadership",
    "How would you train new employees",
    "What is your expected growth in five years",
    "When will you be ready to start",
    "Should we discuss salary now",
    "Can you relocate on short notice",
    "Is there anything you want to ask",
    "Why should we select you",
    "Do you have any questions for us",
    "What tools do you use for productivity",
    "Where do you see yourself next year",
    "Who was your mentor in your last role",
    "Will you attend the training session",
    "Is there any reason you might resign early",
    "Do you like working independently",
    "What are your hobbies outside work",
    "How do you keep up with trends",
    "When did you last learn a new skill",
    "Why do you think you are a good fit",
    "Do you prefer large or small teams",
    "What motivates you every day",
    "Can you work overtime if required",
    "Is it acceptable to call you after hours",
    "What is the best way to contact you",
    "How will you balance this job with personal life",
    "Would you consider working weekends",
    "Is there any issue with background verification",
    "Why do you want to join us",
    "Do you have any pending obligations",
    "What kind of work excites you",
    "How did you handle a difficult teammate",
    "When did you face a major challenge",
    "Do you know about our company culture",
    "Is this your preferred location",
    "Why did you choose this field",
    "How many years of experience do you have",
    "Will you be available for a second interview",
    "What would you like to learn here",
    "How do you manage deadlines",
    "When do you plan to move closer",
    "Is there a reason you switched jobs",
    "Do you feel confident in your skills",
    "What do you hope to accomplish",
    "Would you like to meet the team",
    "Should we share feedback after this interview",
    "Can you summarize your last project",
    "Is remote working acceptable for you",
    "When are you comfortable starting",
    "Who can vouch for your skills",
    "What is your notice period",
    "How did you improve your skills last year",
    "Why do you prefer this role",
    "Are you ready to take on challenges",
    "Do you have any relocation preferences",
    "What do you think about our mission",
    "How will you contribute to the team",
    "Will you be able to handle pressure",
    "Is this the right time for you to change jobs",
    "Do you think you can handle this responsibility",
    "What achievements make you proud",
    "How would you communicate with clients",
    "When did you finish your last role",
    "Why are you passionate about this work",
    "Can you manage remote collaboration",
    "Is teamwork your strength",
    "What do you expect from a manager",
    "Who referred you to this position",
    "When can you finish onboarding",
    "How many projects have you led",
    "Do you want to discuss benefits",
    "Are you willing to mentor others",
    "What motivates you to perform well",
    "How do you organize your work",
    "When can you complete the assignment",
    "Why are you interested in this industry",
    "Is this the type of role you wanted",
    "what time does the store open",
  "how do you fix this error",
  "who is the current president of france",
  "where can I find the nearest gas station",
  "why did the project fail",
  "when is the next holiday",
  "which one is better for programming",
  "could you explain that again",
  "can you tell me more about this",
  "would you mind sharing the details",
  "is there a way to improve this code",
  "how does machine learning actually work",
  "where should I submit the form",
  "who told you about the meeting",
  "what is the meaning of life",
  "why should I choose this plan",
  "when did you last update the document",
  "which laptop has the best battery life",
  "could you show me an example",
  "is the file still available",
  "are we going to get a refund",
  "can this feature be customized",
  "would you consider another option",
  "what ingredients do I need for this recipe",
  "how much does this package cost",
  "why are we having this discussion again",
  "where did you put my keys",
  "who approved the budget",
  "what should I wear for the interview",
  "could you describe your experience",
  "can I see the data report",
  "would it be possible to reschedule",
  "is that really necessary",
  "how many people will be there",
  "where is the safest place to stay",
  "who invented the electric car",
  "why do we use TypeScript",
  "what makes you say that",
  "when was the company founded",
  "which team is in the finals",
  "can you explain recursion to me",
  "would you mind taking a look",
  "is this your final answer",
  "how long does shipping take",
  "where are my packages",
  "who runs the event",
  "why did the code crash",
  "what should I study for the exam",
  "could I get your feedback on this",
  "can you confirm the schedule",
  "is this your first time here",
  "how would you solve this puzzle",
  "where do I upload the file",
  "who manages the database",
  "why are my plants dying",
  "what time do we leave tomorrow",
  "could we talk about this later",
  "can you fix this for me",
  "would you recommend another library",
  "is that a good idea in production",
  "how should I refactor this function",
  "where is the event happening",
  "who is responsible for the report",
  "why should I trust these results",
  "what is the best route to the airport",
  "could you help me move this table",
  "can you switch the meeting time",
  "would you like another coffee",
  "is this compatible with Windows",
  "how did you calculate the total",
  "where is the documentation link",
  "who decided on these requirements",
  "why are there so many delays",
  "what skills are needed for the job",
  "could we push the deadline",
  "can you give me a hand with this",
  "would you check the logs again",
  "is this feature still experimental",
  "how soon can we deploy",
  "where did you save the backup",
  "who was in charge of testing",
  "why do we have these warnings",
  "what should I do next",
  "could you verify these numbers",
  "can you read my handwriting",
  "would you be interested in a demo",
  "is that rule still valid",
  "how many users do we have",
  "where is your office located",
  "who sent the invitation",
  "why did the server go down",
  "what file format do you prefer",
  "could I borrow your laptop",
  "can we roll back the update",
  "would you please sign this form",
  "is that a final estimate",
  "how big is the dataset",
  "where can I see the changelog",
  "who maintains this library",
  "How do you measure success",
  "Is there another way to solve this",
  "Why should we trust that data",
  "What inspired you to start this project",
  "When will the final report be ready",
  "Which platform supports this feature",
  "Could you help me debug this issue",
  "Would you mind explaining that concept again",
  "Can you clarify the requirements",
  "Do you see any potential problems here",
  "Where can I read more about this technology",
  "Who approved these changes",
  "Why does this function return null",
  "How much memory does this process use",
  "Is it possible to postpone the launch",
  "What challenges did you face during testing",
  "When do we need to finalize the budget",
  "Which department handles security",
  "Could you please share your feedback",
  "Would it be okay to move this meeting",
  "Can you show me the updated diagram",
  "Do you think this design is scalable",
  "How are you planning to handle the rollout",
  "Where did you store the backup file",
  "Who will be responsible for maintenance",
   # Background & introduction
    "Can you walk me through your resume",
    "Tell me about your previous roles",
    "How did you get interested in this field",
    "What motivated you to pursue this career path",
    "Could you summarize your experience for me",
    
    # Behavioral
    "Describe a time you had to resolve a conflict on your team",
    "Share an example of working under tight deadlines",
    "What is the most challenging project you worked on",
    "Tell me about a time you disagreed with a coworker",
    "How did you handle a mistake you made in the past",

    # Leadership
    "Have you ever led a team before",
    "What is your leadership style",
    "How do you motivate others to achieve goals",
    "Explain how you delegate tasks to team members",
    "Can you describe a time you inspired others",

    # Problem-solving & analytical
    "What steps do you take to solve complex problems",
    "How do you prioritize tasks when everything is urgent",
    "Can you talk about a time you improved a process",
    "Tell me how you make data-driven decisions",
    "How would you approach learning a new technology",

    # Adaptability & growth
    "How do you handle rapidly changing requirements",
    "Can you share how you adapt to new environments",
    "What skills are you currently working to improve",
    "Where do you see your growth opportunities",
    "How do you manage learning outside your day job",

    # Communication
    "How do you explain technical concepts to nontechnical people",
    "Can you describe your communication style",
    "How do you handle feedback from colleagues",
    "What is your strategy for presenting your ideas",
    "How do you make sure your message is understood",

    # Company / role motivation
    "Why are you interested in this position",
    "What made you apply to our company",
    "What do you know about our products",
    "Why do you think you are a good fit for our team",
    "What attracted you to this industry",

    # Stress / pressure
    "How do you manage stress during high-pressure situations",
    "Can you talk about a time you handled multiple deadlines",
    "What is your approach to working on critical projects",
    "How do you stay focused under pressure",
    "What helps you stay motivated when challenges arise",

    # Future goals
    "Where do you see yourself in five years",
    "What skills do you want to develop in this role",
    "What kind of projects would you like to work on here",
    "What are your long-term career goals",
    "How do you plan to grow professionally",

    # Rhetorical / “soft” style
    "That must have been a difficult choice, right",
    "You probably faced obstacles on that project",
    "Seems like you had to manage competing priorities",
    "Sounds like you learned a lot in that role",
    "You really had to step up to lead the team",


     "Can we shift the deadline",
    "Can we discuss the proposal again",
    "Can we review the budget next week",
    "Can we adjust the requirements",
    "Can we meet earlier tomorrow",
    "Can we make changes to the plan",
    "Can we finalize the deliverables",



    "Tell me about a time you faced adversity",
    "Describe your experience working on cross-functional teams",
    "Walk me through how you prioritized conflicting tasks",
    "Share an example of delivering under pressure",
    "Explain how you approach complex technical problems",
    "Discuss a time you improved a process",
    "Detail the way you handle disagreements with colleagues",
    "Talk about a project where you went above expectations",
    "Show me how you manage your workload",
    "Give an example of mentoring others",

    # rhetorical & conversational
    "That was a tough challenge, wasn't it",
    "You handled that yourself, right",
    "That required quick thinking, yes",
    "They trusted you with that big task, correct",
    "You really pushed the limits there, didn't you",
    "That put you under pressure, no",
    "You solved that problem on your own, right",
    "That had to be stressful, correct",
    "They must have relied on you for that, yes",
    "That was a risky call, wasn't it",

    # clipped, short style
    "But why",
    "And how",
    "So what",
    "Then why",
    "Ok, but who",
    "Really, why",
    "Sure, but when",
    "And why exactly",
    "But how come",
    "Seriously, why",


    "That was by far the finest thing, do you think that way",
    "This seems like a logical solution, don't you agree",
    "That should be enough for the budget, correct",
    "It worked pretty well last year, right",
    "This feature made customers happier, don't you think",
    "We met the deadline easily, is that what you expected",
    "The timeline looks tight, can we handle it",
    "Our team performed great, wouldn't you say",
    "That was a solid improvement, don't you believe",
    "This proposal is reasonable, right",
    "Your approach saved a lot of time, didn't it",
    "Their feedback was mostly positive, correct",
    "This method is sustainable, do you agree",
    "Our plan is efficient, wouldn't you say",
    "It’s clear we reached our goals, right",
    "You handled that issue perfectly, didn't you",
    "The project scope was clear enough, don't you agree",
    "That was the correct decision, yes",
    "The risks are manageable, would you say",
    "We could adapt the strategy, do you think",



    "This was clear, wasn't it",
    "He finished that work, didn't he",
    "We finished on time, correct",
    "The quality is acceptable, yes",
    "They made the right decision, right",
    "You enjoyed working there, didn't you",
    "The plan is strong, correct",
    "She helped with that, right",
    "They signed the deal, yes",
    "Our budget is enough, isn't it",

    # tag confirmations
    "You agree with this, right",
    "It looks stable, doesn't it",
    "You tested that fully, correct",
    "He approved the schedule, didn't he",
    "She reviewed the document, yes",
    "Our numbers are good, right",
    "That was the correct choice, correct",
    "They gave feedback, didn't they",
    "We had enough resources, yes",
    "They accepted the timeline, right",

    # rhetorical agreement
    "This seems fine, don't you think",
    "That is acceptable, correct",
    "You think that approach is solid, right",
    "They probably approved that, yes",
    "The idea sounds good, doesn't it",
    "We handled that well, correct",
    "Our process worked, didn't it",
    "You handled that yourself, right",
    "They were confident, yes",
    "This is the best solution, correct",

    # rhetorical “statement” leading to a question
    "The rollout was fast, wasn't it",
    "We avoided delays, correct",
    "They confirmed the launch, yes",
    "Our product was stable, right",
    "That seemed fair, didn't it",
    "This design is intuitive, correct",
    "They reviewed everything, yes",
    "We prevented issues, didn't we",
    "That change was smooth, right",
    "Our feedback loop was solid, correct",


     "You solved that issue yourself, didn't you",
    "They gave you full control, didn't they",
    "We handled it well, right",
    "That was on schedule, wasn't it",
    "She managed that alone, correct",
    "The plan worked out, didn't it",
    "Our strategy paid off, right",
    "They supported you fully, yes",
    "He finished on time, didn't he",
    "The client was satisfied, correct",
    "You stayed within budget, didn't you",
    "They signed off quickly, right",
    "The rollout went smoothly, didn't it",
    "We finished before deadline, correct",
    "Your team met expectations, yes",
    "That launch was stable, wasn't it",
    "They approved the scope, didn't they",
    "You completed the testing, correct",
    "Our delivery was successful, right",
    "She handled documentation, didn't she",
    "The data was validated, yes",
    "You led the design, didn't you",
    "They gave positive feedback, right",
    "The new process was accepted, correct",
    "You took initiative, didn't you",
    "They adopted your changes, right",
    "He managed that project alone, correct",
    "The budget stayed on track, didn't it",
    "They committed to the timeline, yes",
    "Your results exceeded targets, right",
    "The migration was smooth, correct",
    "They trusted your judgment, didn't they",
    "Our customers were happy, yes",
    "That solution scaled, didn't it",
    "Your team communicated well, right",
    "They relied on your expertise, correct",
    "That estimate was realistic, wasn't it",
    "We solved those bugs quickly, didn't we",
    "They respected the agreement, right",
    "You maintained quality standards, correct",

    "The stakeholders were quite demanding, weren't they",
  "You handled the project alone, didn’t you",
  "They approved the budget quickly, didn’t they",
  "That was a tough deadline, wasn’t it",
  "This change will impact many users, won’t it",

   "The budget was reduced mid-project",
  "We avoided any major production incidents",
  "That was your biggest challenge so far",
  "They assigned you to lead the new initiative",
  "This outcome exceeded the stakeholders’ expectations",
  "They needed quick results, so you delivered early",
  "Your manager supported your promotion",
  "I migrated the entire database to a new server",
  "My team finished the sprint with no blockers",
  "We implemented a new onboarding flow",

  "What is your name",
  "Why did you leave your previous job",
  "How do you prioritize competing deadlines",
  "Could you describe your team’s structure",
  "When did you complete the migration",

   "The stakeholders were quite demanding, weren't they",
  "He finished the migration in record time, didn’t he",
  "They launched the product with a tight budget, didn’t they",
  "You met the client’s expectations, didn’t you",
  "That project turned out really well, didn’t it",
  "The deadlines were aggressive, weren’t they",
  "Your manager supported you all the way, didn’t they",
  "The requirements kept changing, didn’t they",
  "They trusted you with the final sign-off, didn’t they",
  "The team worked overtime to deliver, didn’t they",

  "was the customer satisfied with the final result"
]