statements = [
    "I have five years of experience.",
    "My name is Alice.",
    "I live in New York City.",
    "I graduated in 2019.",
    "I was a team lead at my last job.",
    "I can work on weekends if needed.",
    "I am good with Python and JavaScript.",
    "I love working in a fast-paced environment.",
    "I enjoy collaborating with others.",
    "I relocated last year for a previous job.",
    "I recently completed a certification in AWS.",
    "I am passionate about solving problems.",
    "I am comfortable working remotely.",
    "I prefer working on challenging projects.",
    "I have experience managing budgets.",
    "I value communication and transparency.",
    "I often volunteer in my community.",
    "I focus on continuous improvement.",
    "I can start within two weeks.",
    "I am looking for a growth opportunity.",
    "My last project was a success.",
    "I developed a new process to save time.",
    "I increased efficiency on my team.",
    "I helped train new hires.",
    "I believe in lifelong learning.",
    "I am detail-oriented.",
    "I take ownership of my work.",
    "I respect deadlines and deliver quality.",
    "I’m excited to work in this industry.",
    "I am proactive in solving issues.",
    "My background is in software engineering.",
    "I can adapt to changing priorities.",
    "I respect and value diverse perspectives.",
    "I am motivated by meaningful work.",
    "I take pride in helping customers.",
    "I led a cross-functional team before.",
    "I am organized and plan ahead.",
    "I value constructive feedback.",
    "I contributed to open-source projects.",
    "I am passionate about technology.",
    "I always deliver on commitments.",
    "I work well under pressure.",
    "I recently moved closer to the office.",
    "I am confident in my skill set.",
    "I enjoy tackling difficult challenges.",
    "I am available to work full time.",
    "I completed my degree last year.",
    "I like solving user problems.",
    "I am results-driven.",
    "I have five years of experience",
    "My name is Alice",
    "I live in New York City",
    "I graduated in 2019",
    "I was a team lead at my last job",
    "I can work on weekends if needed",
    "I am good with Python and JavaScript",
    "I love working in a fast-paced environment",
    "I enjoy collaborating with others",
    "I relocated last year for a previous job",
    "I recently completed a certification in AWS",
    "I am passionate about solving problems",
    "I am comfortable working remotely",
    "I went to the store yesterday",
    "he finished the project on time",
    "this package includes free delivery",
    "my dog is very friendly",
    "we are working on the new feature",
    "she lives in a small town",
    "they enjoy hiking every weekend",
    "I will send you the files later",
    "the sun sets around 7 pm in summer",
    "there is no way to fix this bug easily",
    "she taught herself to play guitar",
    "we have finished all the tests",
    "I prefer working remotely",
    "my team is growing steadily",
    "the restaurant closes at 9 pm",
    "this plan might save us money",
    "I spoke to the manager yesterday",
    "their flight arrives in the morning",
    "the workshop was very informative",
    "he decided to learn a new language",
    "we cannot release the code yet",
    "the database is running out of space",
    "I will handle the deployment",
    "the kids are playing outside",
    "she has already signed the contract",
    "we follow agile practices here",
    "the cat likes to sleep on my desk",
    "I just finished reading the book",
    "my laptop battery is low",
    "he plans to study medicine next year",
    "we should schedule a call tomorrow",
    "the event went well overall",
    "she shared her travel photos with me",
    "I have uploaded the new document",
    "their product has amazing reviews",
    "the bug was fixed last week",
    "I prefer tea over coffee",
    "our team is doing great",
    "he works as a software engineer",
    "they built the app with React",
    "I am learning to cook new dishes",
    "the weather is very hot today",
    "I love spending time in nature",
    "she drew a beautiful painting",
    "we will review your application soon",
    "my phone is charging right now",
    "they moved to a different city",
    "he likes to work late at night",
    "the test results look promising",
    "I have been waiting for your reply",
    "our meeting starts in an hour",
    "they finished the marathon together",
    "I bought a new pair of headphones",
    "the water is too cold to swim",
    "my friend just graduated from college",
    "she works in human resources",
    "we created a custom solution",
    "his presentation was impressive",
    "I need to submit this by Friday",
    "the design looks modern and fresh",
    "our server crashed during deployment",
    "I hope you have a great day",
    "he will travel abroad next month",
    "the kitchen renovation is complete",
    "I received your email this morning",
    "they own a small coffee shop",
    "the garden has many colorful flowers",
    "she learned to drive last year",
    "my password was changed recently",
    "we completed the audit successfully",
    "I have to leave for an appointment",
    "the application supports dark mode",
    "he has a good sense of humor",
    "the product was shipped on time",
    "I updated the documentation yesterday",
    "the children are reading quietly",
    "we used Python for data analysis",
    "the hotel offers free breakfast",
    "she joined the team last quarter",
    "the code is open source",
    "I appreciate your support",
    "the music sounds amazing",
    "he made significant progress",
    "my internet connection is stable now",
    "the price seems fair to me",
    "she looks very confident today",
    "we will discuss the results later",
    "I have another call in ten minutes",
    "they replaced the broken parts",
    "the updates are being rolled out",
    "I saw that movie last weekend",
    "the meeting room is on the second floor",
    "she started learning French recently",
    "we hosted the event online",
    "the task was completed ahead of schedule",
    "he takes care of his grandparents",
    "my parents visited last month",
    "the conference starts next week",
    "I lost my keys this morning",
    "they invested in renewable energy",
    "she is studying for her exams",
    "The team delivered the project ahead of schedule",
    "Our customers are satisfied with the latest update",
    "He has worked here for more than ten years",
    "The servers were upgraded last weekend",
    "I enjoy working with talented people",
    "She presented a very convincing argument",
    "The application runs smoothly on Android",
    "They are working on a new payment system",
    "My manager approved the expense report",
    "We deployed the patch to production yesterday",
    "This process reduces our operating costs",
    "Their product reached a wider audience",
    "I prefer using dark mode for coding",
    "The office will be closed on Friday",
    "He created an impressive user interface",
    "The analysis revealed some hidden bugs",
    "She has experience leading remote teams",
    "We collected feedback from multiple sources",
    "Our next release is scheduled for next month",
    "They implemented stricter security controls",
    "I took a break after a long workday",
    "The contract was finalized with all stakeholders",
    "Their marketing campaign gained a lot of attention",
    "She managed a team of five developers",
  "We delivered the migration ahead of schedule",
  "They completed the security audit last month",
  "The feature rollout happened in three phases",
  "I worked with cross functional stakeholders",
  "We reduced system downtime through automation",
  "He gained experience in cloud architecture",
  "The client approved the final deliverables",
  "Our onboarding flow improved user engagement",
  "They scheduled the product launch for July",
  "I analyzed customer feedback after deployment",
  "We aligned our roadmap with business strategy",
  "They increased the testing coverage last sprint",
  "My team implemented a reusable component library",
  "We solved major production issues after the hotfix",
  "The migration was completed with no data loss",
  "They requested additional documentation from our team",
  "Our quarterly results exceeded initial expectations",
  "The development team removed technical debt efficiently",
  "We introduced a mentoring program for junior staff",
  "They built a dashboard to track all KPIs",
  "The timeline stayed consistent throughout the phases",
  "Our security policies were updated after the audit",
  "They offered us a contract extension last quarter",
  "We migrated most systems to a cloud environment",
  "The stakeholder feedback was positive after launch",
  "They deployed the new feature in a staged rollout",
  "Our team collaborated closely with designers",
  "I completed the API integration before the deadline",
  "They reviewed the requirements with the client again",
  "The system performance improved after code optimization",
  "We finalized the testing scenarios last week",
  "They closed critical bugs before going live",
  "My manager supported the project vision from the start",
  "We created a shared component library for reuse",
  "The operations team resolved the network issues",
  "They delivered high availability through load balancing",
  "Our process documentation helped reduce errors",
  "We captured valuable insights from user interviews",
  "The incident response plan was successfully tested",
  "They upgraded the database infrastructure recently",
  "Our metrics showed better adoption this month",
  "The leadership team recognized our achievements",
  "We reduced manual tasks through scripting",
  "They shared a detailed retrospective with lessons learned",
  "Our devops pipeline improved deployment speed",
  "They prepared a migration checklist for knowledge transfer",
  "I contributed to several cross team initiatives",
  "We maintained system stability during high traffic events",
  "They launched a security awareness campaign internally"
    "My colleagues helped me resolve the issue",
    "We planned to scale the infrastructure soon",

    "I completed the project within the deadline",
  "They launched the new platform last month",
  "My team improved system performance by 30%",
  "The migration was completed with zero downtime",
  "We maintained full data integrity during the rollout",
  "They signed off on the final deliverables yesterday",
  "Our department reduced costs by implementing automation",
  "The feedback from stakeholders was overwhelmingly positive",
  "We handled all critical bugs before going live",
  "The security audit found no major vulnerabilities",
  "I led a cross-functional team across two countries",
  "They invited me to join the steering committee",
  "We built a reusable component library for the entire organization",
  "The testing phase concluded without any blockers",
  "I designed a solution to improve onboarding speed",
  "Our infrastructure was upgraded with minimal disruption",
  "They recognized our team’s contribution with an award",
  "I proactively identified performance bottlenecks",
  "The project outcome surpassed client expectations",
  "We achieved a record number of customer sign-ups that quarter",

   "The project scope was finalized after stakeholder review",
  "We delivered the first release ahead of schedule",
  "They increased the team size to meet deadlines",
  "Our budget was approved without revisions",
  "I collaborated with cross-functional teams to complete the rollout",
  "They recognized our contributions in the quarterly review",
  "The client extended the contract for another year",
  "We migrated the infrastructure with minimal issues",
  "The technical debt was significantly reduced last quarter",
  "My team maintained service uptime above 99%",
  "They appreciated our thorough documentation",
  "The security policy was updated following the audit",
  "We onboarded five new engineers last month",
  "The design guidelines were consolidated to improve consistency",
  "We improved the deployment pipeline by automating tests",
  "The customer feedback was very positive after the launch",
  "Our approach was aligned with industry best practices",
  "They requested additional training sessions after deployment",
  "I negotiated the vendor contracts for better pricing",
  "Our quarterly results exceeded expectations by 20%",
  "We introduced a mentorship program for junior staff",
  "The engineering team successfully modernized the legacy system",
  "We documented every phase of the migration process",
  "They transitioned all services to a microservices architecture",
  "My manager supported my promotion to a leadership role",

   "We avoided any major production incidents",
  "That was your biggest challenge so far",
  "They assigned you to lead the new initiative",
  "This outcome exceeded the stakeholders’ expectations",
  "They needed quick results, so you delivered early",
  "Your manager supported your promotion",
  "Our team built a reliable deployment process",
  "They invested heavily in security upgrades",
  "We transitioned to a new tech stack last year",
  "The client renewed the contract for another year",
  "They finalized the budget after two rounds of approval",
  "My role expanded to include stakeholder management",
  "We stabilized the production environment quickly",
  "Our onboarding time improved by 50% last quarter",
  "They recognized our delivery team with an award"
]